# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 兰州大学开源社区镜像站
# title: 北京外国语大学开源软件镜像站
school: 兰州大学
# school: 北京外国语大学
brand: Lanzhou University Open Source Mirror
operator: 兰州大学开源社区
author: Lanzhou University Open Source Society
desc: 致力于为国内和校内用户提供高质量的开源软件镜像、Linux 镜像源服务，帮助用户更方便地获取开源软件。本镜像站由兰州大学开源社区负责运行维护。
# operator: 北外信息技术中心
logo: false
meow_404: true
issue_tag: tuna
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirrors.lzu.edu.cn/"
hostname: "mirrors.lzu.edu.cn"
urlv4: "https://mirrors4.lzu.edu.cn"
urlv6: "https://mirrors6.lzu.edu.cn"
# aosp: "aosp.tuna.tsinghua.edu.cn"
# arch_archive: "arch-archive.tuna.tsinghua.edu.cn"
# pypi: "pypi.tuna.tsinghua.edu.cn"
homelink: "https://mirrors.lzu.edu.cn/"
hide_navbar: false
hide_download: false
hide_server_status: false

hide_mirrorz: false
mirrorz_desc: 校园网联合镜像站
mirrorz_link: "https://mirrors.cernet.edu.cn/list"
mirrorz_help_link: "https://help.mirrors.cernet.edu.cn/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

plugins:
    - jekyll-babel
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]

# sponsors:
#     megvii:
#         name: "旷视科技有限公司"
#         link: "https://megvii.com/"
#         short: "旷视"
#         eng: "Megvii Technology Ltd."
#         logo: "megvii-s"
#     huawei:
#         name: "华为技术有限公司"
#         link: "https://huawei.com/"
#         short: "华为"
#         eng: "Huawei Technologies Co., Ltd."
#         logo: "huawei"

# poweredbys:
#     kunpeng: "海思<sup>®</sup> Kunpeng<sup>®</sup> 920 处理器"

# vim: ts=2 sts=2 sw=2 expandtab
